#!/usr/bin/python

import netmeter_config

toMiB = 1024.0*1024.0

with open(FNAME_TOTAL_RCV, "r") as f:
	total_rcv = float(f.readline()) / toMiB

with open(FNAME_TOTAL_SENT, "r") as f:
	total_sent = float(f.readline()) / toMiB

with open(FNAME_SESS_RCV, "r") as f:
	sess_rcv = float(f.readline()) / toMiB

with open(FNAME_SESS_SENT, "r") as f:
	sess_sent = float(f.readline()) / toMiB

print "Received: \nSession:", sess_rcv, " MiB\nTotal:", (total_rcv+sess_rcv), "MiB\nSent: \nSession:", sess_sent, "MiB\nTotal:", (total_sent+sess_sent), "MiB"