#!/usr/bin/python

# Copyright (C) 2012  tdubourg, License: see LICENSE file in same folder

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License v3
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from signal import alarm
from signal import pause
import signal
from netmeter_config import *


# Utilities functions: 

def doNothing(arg1, arg2):
	global DBG
	if DBG:
		print "Doing nothing"
	return;

def replace_content_in_file(fname, newcontent):
	with open(fname, "w+") as f:
		f.write(str(newcontent))

def open_in_read_or_create(fname):
	try:
		f = open(fname, "r+")
	except IOError as e:
		f = open(fname, "w+")
	return f


interfaces = get_interfaces()

if DBG:
	print interfaces

signal.signal(signal.SIGALRM, doNothing)

def put_session_in_total_count_for_interface(i):
	f_tot_rcv = open_in_read_or_create(fname_with_interface(FNAME_TOTAL_RCV, i))
	f_tot_sent = open_in_read_or_create(fname_with_interface(FNAME_TOTAL_SENT, i))

	f_sess_rcv = open_in_read_or_create(fname_with_interface(FNAME_SESS_RCV, i))
	f_sess_sent = open_in_read_or_create(fname_with_interface(FNAME_SESS_SENT, i))

	try:
		# if DBG:
			# print "For interface", i, "former value was: up", int(f_sess_rcv.readline()), 'down', int(f_sess_sent.readline())
		try:
			prev_total_rcv = int(f_tot_rcv.readline())
			prev_total_sent = int(f_tot_sent.readline())
		except ValueError:
			prev_total_rcv = 0
			prev_total_sent = 0
		total_rcv =  prev_total_rcv + int(f_sess_rcv.readline())
		total_sent = prev_total_sent + int(f_sess_sent.readline())
	except ValueError as e:
		if DBG:
			print e
		total_rcv = 0
		total_sent = 0

	f_tot_rcv.close()
	f_tot_sent.close()
	f_sess_sent.close()
	f_sess_rcv.close()

	# Updating the TOTAL files: 
	if DBG:
		print "Replacing totals by: down", total_rcv, "up", total_sent
	replace_content_in_file(fname_with_interface(FNAME_TOTAL_RCV, i), total_rcv)
	replace_content_in_file(fname_with_interface(FNAME_TOTAL_SENT, i), total_sent)

# Updating the total value by adding the vlue of last session	
former_values = {}
for i in interfaces:
	former_values[i] = {'rcv': 0, 'sent': 0}
	put_session_in_total_count_for_interface(i)

session_recv = 0
session_sent = 0


# Start the never-ending story !
while True:
	if DBG:
		print "looping"
	with open(FNAME_MONITOR) as f:
		for l in f.readlines():
			m = r_interface_line.search(l)
			if m is not None:
				interface_name = m.group(1)
				if DBG:
					print "Current interface:", interface_name
					print "Group:", m.group(2), "\n\n"
				m = r_figure.findall(m.group(2))
				if m is not None:
					session_recv = int(m[0])
					session_sent = int(m[8])
					
					# If the connection has been reset without restarting the computer
					# Then put the current session in the total counts before resetting it
					if session_recv < former_values[interface_name]["rcv"] or session_sent < former_values[interface_name]["sent"]:
						if DBG:
							print "Connection was reset for interface", interface_name
						put_session_in_total_count_for_interface(interface_name)
					
					former_values[interface_name]["rcv"] = session_recv
					former_values[interface_name]["sent"] = session_sent
					
					replace_content_in_file(fname_with_interface(FNAME_SESS_RCV, interface_name), session_recv)
					replace_content_in_file(fname_with_interface(FNAME_SESS_SENT, interface_name), session_sent)
					if DBG:
						print "Received:", session_recv, "Sent:", session_sent
			elif DBG:
				print "The pattern was not matched against the line l=", l
	alarm(INTERVAL)
	pause()










