#!/usr/bin/python

import re
from signal import alarm
from signal import pause
import signal
import netmeter_config


# Utilities functions: 

def doNothing(arg1, arg2):
	global DBG
	if DBG:
		print "Doing nothing"
	return;

def replace_content_in_file(fname, newcontent):
	with open(fname, "w+") as f:
		f.write(str(newcontent))

def open_in_read_or_create(fname):
	try:
		f = open(fname, "r+")
	except IOError as e:
		f = open(fname, "w+")
	return f

r_interface_line = re.compile("^ *([a-zA-z0-9]+):(( +([0-9]+)){16})\n?$")
r_figure = re.compile("([0-9]+)")

interfaces = get_interfaces()

if DBG:
	print interfaces

signal.signal(signal.SIGALRM, doNothing)

# Updating the total value by adding the vlue of last session	
for i in interfaces:
	f_tot_rcv = open_in_read_or_create(fname_with_interface(FNAME_TOTAL_RCV, i))
	f_tot_sent = open_in_read_or_create(fname_with_interface(FNAME_TOTAL_SENT, i))

	f_sess_rcv = open_in_read_or_create(fname_with_interface(FNAME_TOTAL_SENT, i))
	f_sess_sent = open_in_read_or_create(fname_with_interface(FNAME_TOTAL_SENT, i,))

	try:
		total_rcv = int(f_tot_rcv.readline()) + int(f_sess_rcv.readline())
		total_sent = int(f_tot_sent.readline()) + int(f_sess_sent.readline())
	except ValueError:
		total_rcv = 0
		total_sent = 0

	f_tot_rcv.close()
	f_tot_sent.close()
	f_sess_sent.close()
	f_sess_rcv.close()

	# Updating the TOTAL files: 
	replace_content_in_file(fname_with_interface(FNAME_TOTAL_RCV, i), total_rcv)
	replace_content_in_file(fname_with_interface(FNAME_TOTAL_SENT, i), total_sent)

session_recv = 0
session_sent = 0
# Start the never-ending story !
while True:
	if DBG:
		print "looping"
	with open(FNAME_MONITOR) as f:
		for l in f.readlines():
			m = r_interface_line.search(l)
			if m is not None:
				interface_name = m.group(1)
				if DBG:
					print "Group:", m.group(2), "\n\n"
				m = r_figure.findall(m.group(2))
				if m is not None:
					session_recv = int(m[0])
					session_sent = int(m[8])
					replace_content_in_file(fname_with_interface(FNAME_SESS_RCV), session_recv)
					replace_content_in_file(FNAME_SESS_SENT, session_sent)
					if DBG:
						print "Received:", session_recv, "Sent:", session_sent
			elif DBG:
				print "The pattern was not matched against the line l=", l
	alarm(INTERVAL)
	pause()










